CC=gcc

sumCalc.o: sumCalc.c
	$(CC) -c sumCalc.c

meanCalc.o: meanCalc.c
	$(CC) -c meanCalc.c

standardDev.o: standardDev.c
	$(CC) -c standardDev.c

myStats: myStats.c sumCalc.o meanCalc.o standardDev.o myStats.h 
	$(CC) -o myStats sumCalc.o meanCalc.o standardDev.o myStats.c -lm

clean: *.o
	rm -f *.o
	rm -f myStats
